name: Repository Lister

on:
  workflow_dispatch:
    inputs:
      target_account:
        description: "Target GitHub username/org"
        required: true

jobs:
  list_repos:
    runs-on: ubuntu-latest
    outputs:
      repo_list: ${{ steps.list-repos.outputs.repo_list }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install PyGithub==1.59.0

      - name: List repositories
        id: list-repos
        env:
          GITHUB_TOKEN: ${{ secrets.MASTER_TOKEN }}
          TARGET_ACCOUNT: ${{ inputs.target_account }}
        run: |
          python -c "
          from github import Github, GithubException
          import os
          import json

          token = os.getenv('GITHUB_TOKEN')
          target_account = os.getenv('TARGET_ACCOUNT')
          
          try:
              g = Github(token)
              current_user = g.get_user().login
              
              # Determine if target is organization or user
              try:
                  # Try to get as organization
                  org = g.get_organization(target_account)
                  is_org = True
              except GithubException:
                  # If fails, treat as user
                  user = g.get_user(target_account)
                  is_org = False
              
              # Fetch repositories based on account type
              if is_org:
                  repos = org.get_repos(affiliation='owner', visibility='all')
              else:
                  # For user accounts, get all repositories
                  repos = user.get_repos()
              
              # Filter repositories to only those owned by the target account
              repo_list = []
              for repo in repos:
                  # For organizations, all repos are owned
                  if is_org:
                      repo_list.append(repo.name)
                  # For users, only include repos they own
                  elif repo.owner.login.lower() == target_account.lower():
                      repo_list.append(repo.name)
              
              # Save to file for artifact
              with open('repo-list.json', 'w') as f:
                  json.dump(repo_list, f)
                  
              # Set output using GitHub Actions environment file
              with open(os.environ['GITHUB_OUTPUT'], 'a') as f:
                  f.write(f'repo_list={json.dumps(repo_list)}')
                  
              print(f'Found {len(repo_list)} repositories for {target_account}')
              
          except Exception as e:
              print(f'Error: {str(e)}')
              exit(1)
          "

      - name: Upload repository list
        uses: actions/upload-artifact@v4
        with:
          name: repo-list
          path: repo-list.json
